server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
    timeout: 60000

mybatis:
  configuration:
    map-underscore-to-camel-case: true  #驼峰命名规则
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # sql的日志打印

